- name: nginx install and run
  hosts: nginx #provide ngnix pvt ip_add in inventory
  become: yes
  serial: 3 #play level
  tasks:
  - name: install nginx
    ansible.builtin.package: #heterongenous module that can work for all distros
      name: nginx
      state: present
  
  - name: run nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes